
CREATE TABLE base_id (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT) ENGINE=MyISAM AUTO_INCREMENT=10000000;

CREATE TABLE base_ranking (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT) ENGINE=MyISAM;

